### ISSUE TITLE
JSON arrays don't work

### ISSUE THREAD

**Issue by DonaldRecord** [Microsoft/slow-cheetah#161]
Hello! One of the JSON files I am bound to using is a JSON array - like so:
```
[
    "string1",
    "string2",
    "string3",
    "string4"
]
```
It is an array - not an object.
When building the project, I get the following error:
`MSB4018 The "SlowCheetah.TransformTask" task failed unexpectedly.`
With the following stack trace:
```
Newtonsoft.Json.JsonReaderException: Error reading JObject from JsonReader. Current JsonReader item is not an object: StartArray. Path '', line 1, position 1.
   at Newtonsoft.Json.Linq.JObject.Load(JsonReader reader, JsonLoadSettings settings)
   at Microsoft.VisualStudio.Jdt.JsonTransformation.SetTransform(Stream transformStream)
   at Microsoft.VisualStudio.Jdt.JsonTransformation..ctor(String transformFile, IJsonTransformationLogger logger)
   at Microsoft.VisualStudio.SlowCheetah.JsonTransformer.Transform(String sourcePath, String transformPath, String destinationPath)
   at Microsoft.VisualStudio.SlowCheetah.TransformTask.Execute()
   at Microsoft.Build.BackEnd.TaskExecutionHost.Microsoft.Build.BackEnd.ITaskExecutionHost.Execute()
   at Microsoft.Build.BackEnd.TaskBuilder.<ExecuteInstantiatedTask>d__26.MoveNext()	TransferPaper.Web	C:\Users\recordd\.nuget\packages\microsoft.visualstudio.slowcheetah\3.1.66\build\Microsoft.VisualStudio.SlowCheetah.targets	109	
```

**Comment by DonaldRecord** [comment]
Is this something that is intentionally not supported?

**Comment by ameser83** [comment]
Debbuging the code I found that this issue is related to Newtonsoft.json library, not in slow cheetah,
 you can verify this with running your example directly with Newtonsoft.json.

                var parseArray = JObject.Parse(YourJsonString);
                var parseArray = JArray.Parse(YourJsonString);

**Comment by davilimap** [comment]
This is in fact an issue with Newtonsoft.JSON since in arrays, there's not really a way to differentiate between the objects right now.
Theoretically we could implement some logic to do this, you can request that in the [JDT](https://github.com/Microsoft/json-document-transforms) Repo, the engine SlowCheetah uses for JSON transforms
