### ISSUE TITLE
Transform fails when project is targetting multiple frameworks

### ISSUE THREAD

**Issue by CraigRichards** [microsoft/slow-cheetah#290]
Hi,
I regularly target multiple frameworks in the work I do and this constantly fails due to file-locking issues. I love this product and hope you can patch this easily.

Reproduction is simple.
I target multiple frameworks as the API client should work for all framework versions and my tests required different configurations depending on the environment.   <TargetFrameworks>net4;net45;net451;net452;net461;net462;net47;net471;net472;net48;netcoreapp3.0;netcoreapp3.1;net5;net6;net7</TargetFrameworks>

![image](https://github.com/microsoft/slow-cheetah/assets/239825/824a1f59-a09e-483b-b883-5c00b52ba6fc)

# Error Message
Severity	Code	Description	Project	File	Line	Suppression State
Error	MSB4018	The "SlowCheetah.TransformTask" task failed unexpectedly.
System.IO.IOException: The process cannot access the file 'd:\Api.Client.Tests\appSettings.Dev3.json' because it is being used by another process.
   at System.IO.__Error.WinIOError(Int32 errorCode, String maybeFullPath)
   at System.IO.FileStream.Init(String path, FileMode mode, FileAccess access, Int32 rights, Boolean useRights, FileShare share, Int32 bufferSize, FileOptions options, SECURITY_ATTRIBUTES secAttrs, String msgPath, Boolean bFromProxy, Boolean useLongPath, Boolean checkHost)
   at System.IO.FileStream..ctor(String path, FileMode mode, FileAccess access, FileShare share)
   at Microsoft.VisualStudio.Jdt.JsonTransformation..ctor(String transformFile, IJsonTransformationLogger logger)
   at Microsoft.VisualStudio.SlowCheetah.JsonTransformer.Transform(String sourcePath, String transformPath, String destinationPath)
   at Microsoft.VisualStudio.SlowCheetah.TransformTask.Execute()
   at Microsoft.Build.BackEnd.TaskExecutionHost.Microsoft.Build.BackEnd.ITaskExecutionHost.Execute()
   at Microsoft.Build.BackEnd.TaskBuilder.<ExecuteInstantiatedTask>d__26.MoveNext()	Api.Client.Tests	D:\licensing-api\packages-cache\microsoft.visualstudio.slowcheetah\4.0.50\build\Microsoft.VisualStudio.SlowCheetah.targets	115

**Comment by mwpowellhtx** [comment]
I'm running into a similar issue, my targets are not running properly, like none whatsoever, seems like, under multi-targeting scenarios. Turns out, may be an issue with how `NuGet` is now treating `build/` and `buildMultiTargeting/`, `.props` and `.targets` consumption. It is something probably, more than likely, new, since the time of during which these packages had last published. That's my two cents for what it's worth. I am working to resolve just that matter right now, in my packages.
