### ISSUE TITLE
Can't install VSIX for VS 2022 Enterprise edition

### ISSUE THREAD

**Issue by tperriVV** [microsoft/slow-cheetah#300]
7/1/2024 1:41:13 PM - Microsoft VSIX Installer
7/1/2024 1:41:13 PM - -------------------------------------------
7/1/2024 1:41:13 PM - vsixinstaller.exe version:
7/1/2024 1:41:13 PM - 17.6.2157+g15b2a813de
7/1/2024 1:41:13 PM - -------------------------------------------
7/1/2024 1:41:13 PM - Command line parameters:
7/1/2024 1:41:13 PM - C:\Program Files (x86)\Microsoft Visual Studio\Installer\resources\app\ServiceHub\Services\Microsoft.VisualStudio.Setup.Service\VSIXInstaller.exe,C:\Users\therese.perri\Downloads\Microsoft.VisualStudio.SlowCheetah.vsix
7/1/2024 1:41:13 PM - -------------------------------------------
7/1/2024 1:41:13 PM - Microsoft VSIX Installer
7/1/2024 1:41:13 PM - -------------------------------------------
7/1/2024 1:41:13 PM - Initializing Install...
7/1/2024 1:41:13 PM - Searching for applicable products...
7/1/2024 1:41:14 PM - Found installed product - Visual Studio Enterprise 2022 LTSC 17.4
7/1/2024 1:41:14 PM - Found installed product - Global Location
7/1/2024 1:41:14 PM - Extension Details...
7/1/2024 1:41:14 PM - 	Identifier         : 9eb9f150-fcc9-4db8-9e97-6aef2011017c
7/1/2024 1:41:14 PM - 	Name               : SlowCheetah
7/1/2024 1:41:14 PM - 	Author             : Microsoft Corporation
7/1/2024 1:41:14 PM - 	Version            : 3.2.18.4433
7/1/2024 1:41:14 PM - 	Description        : Transform xml and json files at build time based on configuration. Contains tooling to assist in the creation and previewing of transform files.
7/1/2024 1:41:14 PM - 	Locale             : en-US
7/1/2024 1:41:14 PM - 	MoreInfoURL        : https://github.com/Microsoft/slow-cheetah
7/1/2024 1:41:14 PM - 	InstalledByMSI     : False
7/1/2024 1:41:14 PM - 	SupportedFrameworkVersionRange : [4.5,)
7/1/2024 1:41:14 PM - 	SignatureState     : ValidSignature
7/1/2024 1:41:14 PM - 	SignedBy           : Microsoft Corporation
7/1/2024 1:41:14 PM - 	Certificate Info   : 
7/1/2024 1:41:14 PM - 		-------------------------------------------------------
7/1/2024 1:41:14 PM - 		[Subject]       : CN=Microsoft Corporation, OU=OPC, O=Microsoft Corporation, L=Redmond, S=Washington, C=US
7/1/2024 1:41:14 PM - 		[Issuer]        : CN=Microsoft Code Signing PCA 2010, O=Microsoft Corporation, L=Redmond, S=Washington, C=US
7/1/2024 1:41:14 PM - 		[Serial Number] : 330000026ECE6AE5984BFC96A900000000026E
7/1/2024 1:41:14 PM - 		[Not Before]    : 9/6/2018 5:00:30 PM
7/1/2024 1:41:14 PM - 		[Not After]     : 9/6/2019 5:00:30 PM
7/1/2024 1:41:14 PM - 		[Thumbprint]    : 99B6246883B4B32EA59AE18B36945D205A876800
7/1/2024 1:41:14 PM - 	Supported Products : 
7/1/2024 1:41:14 PM - 		Microsoft.VisualStudio.Community
7/1/2024 1:41:14 PM - 			Version : [14.0,17.0)
7/1/2024 1:41:14 PM - 			ProductArchitecture : x86
7/1/2024 1:41:14 PM - 	References         : 
7/1/2024 1:41:14 PM - 	Prerequisites      : 
7/1/2024 1:41:14 PM - 		-------------------------------------------------------
7/1/2024 1:41:14 PM - 		Identifier   : Microsoft.VisualStudio.Component.CoreEditor
7/1/2024 1:41:14 PM - 		Name         : Visual Studio core editor
7/1/2024 1:41:14 PM - 		Version      : [15.0,)
7/1/2024 1:41:14 PM - Signature Details...
7/1/2024 1:41:14 PM - 	Extension is signed with a valid signature.
7/1/2024 1:41:14 PM - VSIXInstaller.NoApplicableSKUsException: This extension is not installable on any currently installed products.
   at VSIXInstaller.ExtensionService.GetInstallableDataImpl(String vsixPath, String extensionPackParentName, Boolean isRepairSupported, IStateData stateData, IEnumerable`1& skuData)
   at VSIXInstaller.ExtensionService.GetInstallableData(String vsixPath, String extensionPackParentName, Boolean isRepairSupported, IStateData stateData, IEnumerable`1& skuData)
   at VSIXInstaller.ExtensionPackService.IsExtensionPack(IStateData stateData, Boolean isRepairSupported)
   at VSIXInstaller.ExtensionPackService.ExpandExtensionPackToInstall(IStateData stateData, Boolean isRepairSupported)
   at VSIXInstaller.App.Initialize(Boolean isRepairSupported)
   at VSIXInstaller.App.Initialize()
   at System.Threading.Tasks.Task`1.InnerInvoke()
   at System.Threading.Tasks.Task.Execute()
   
   
Please advise.

Thanks!
Therese

**Comment by tperriVV** [comment]
I was able to install through Manage Extensions.  I got this error from clicking the download link in the readme.txt file that is included in the SlowCheetah nuget package.
