### ISSUE TITLE
vsix failed to install on VS 2013 Ultimate

### ISSUE THREAD

**Issue by ArtyP** [Microsoft/slow-cheetah#88]
> 02.10.2017 12:27:24 - Microsoft VSIX Installer
> 02.10.2017 12:27:24 - -------------------------------------------
> 02.10.2017 12:27:24 - Initializing Install...
> 02.10.2017 12:27:24 - Extension Details...
> 02.10.2017 12:27:24 - 	Identifier      : 9eb9f150-fcc9-4db8-9e97-6aef2011017c
> 02.10.2017 12:27:24 - 	Name            : SlowCheetah
> 02.10.2017 12:27:24 - 	Author          : Microsoft Corporation
> 02.10.2017 12:27:24 - 	Version         : 3.0.61.18192
> 02.10.2017 12:27:24 - 	Description     : Transform xml and json files at build time based on configuration. Contains tooling to assist in the creation and previewing of transform files.
> 02.10.2017 12:27:24 - 	Locale          : en-US
> 02.10.2017 12:27:24 - 	MoreInfoURL     : https://github.com/Microsoft/slow-cheetah
> 02.10.2017 12:27:24 - 	InstalledByMSI  : False
> 02.10.2017 12:27:24 - 	SupportedFrameworkVersionRange : [4.5,)
> 02.10.2017 12:27:24 - 
> 02.10.2017 12:27:24 - 	SignedBy        : Microsoft Corporation
> 02.10.2017 12:27:24 - 	Certificate Info : [Subject]
>   CN=Microsoft Corporation, OU=MOPR, OU=OPC, O=Microsoft Corporation, L=Redmond, S=Washington, C=US
> ...
> 02.10.2017 12:27:24 - 	Supported Products : 
> 02.10.2017 12:27:24 - 		Microsoft.VisualStudio.Community
> 02.10.2017 12:27:24 - 			Version : [14.0,16.0)
> 02.10.2017 12:27:24 - 
> 02.10.2017 12:27:24 - 	References      : 
> 02.10.2017 12:27:24 - 		-------------------------------------------------------
> 02.10.2017 12:27:24 - 		Identifier   : Microsoft.VisualStudio.MPF.11.0
> 02.10.2017 12:27:24 - 		Name         : Visual Studio MPF 11.0
> 02.10.2017 12:27:24 - 		Version      : [11.0]
> 02.10.2017 12:27:24 - 		MoreInfoURL  : 
> 02.10.2017 12:27:24 - 		Nested       : No
> 02.10.2017 12:27:24 - 
> 02.10.2017 12:27:24 - 
> 02.10.2017 12:27:24 - Searching for applicable products...
> 02.10.2017 12:27:24 - Found installed product - Microsoft Visual Studio Ultimate 2013
> 02.10.2017 12:27:24 - Found installed product - Microsoft Visual Studio Premium 2013
> 02.10.2017 12:27:24 - Found installed product - Microsoft Visual Studio Professional 2013
> 02.10.2017 12:27:24 - Found installed product - Microsoft Visual Studio 2013 Shell (Integrated)
> 02.10.2017 12:27:24 - Found installed product - Global Location
> 02.10.2017 12:27:24 - VSIXInstaller.NoApplicableSKUsException: This extension is not installable on any currently installed products.
>    at VSIXInstaller.App.InitializeInstall()
>    at System.Threading.Tasks.Task.InnerInvoke()
>    at System.Threading.Tasks.Task.Execute()
>

**Comment by ArtyP** [comment]
I have installed from [here](https://github.com/sayedihashimi/slow-cheetah/releases/tag/v2.5.48).
