### ISSUE TITLE
Support only for JObjects during json transformation

### ISSUE THREAD

**Issue by CecilK** [Microsoft/slow-cheetah#92]
My .Json file is an array of objects, so the transformation fails with the following error: 

The "SlowCheetah.TransformTask" task failed unexpectedly.
Newtonsoft.Json.JsonReaderException: Error reading JObject from JsonReader. Current JsonReader item is not an object: StartArray. Path '', line 1, position 1.
   at Newtonsoft.Json.Linq.JObject.Load(JsonReader reader, JsonLoadSettings settings)
   at Microsoft.VisualStudio.Jdt.JsonTransformation.SetTransform(Stream transformStream)
   at Microsoft.VisualStudio.Jdt.JsonTransformation..ctor(String transformFile, IJsonTransformationLogger logger)
   at Microsoft.VisualStudio.SlowCheetah.JsonTransformer.Transform(String source, String transform, String destination)
   at Microsoft.VisualStudio.SlowCheetah.TransformTask.Execute()
   at Microsoft.Build.BackEnd.TaskExecutionHost.Microsoft.Build.BackEnd.ITaskExecutionHost.Execute()
   at Microsoft.Build.BackEnd.TaskBuilder.<ExecuteInstantiatedTask>d__26.MoveNext()	

```
[
    {
        "Id": "405",
         .....
    }
]
```

**Comment by davilimap** [comment]
This is a slight gap in [JDT,](https://github.com/Microsoft/json-document-transforms) the tranformation engine SlowCheetah uses for JSON. Right now, the root of the json file cannot be an array, since that would lead to problems identifying the elements in the array between the source and transformation file. While this is possible, it would require some additional logic on the JDT side, so I'll reopen this bug over there.
